version: '3'
services:
  db:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_USERNAME: viewing_party
      POSTGRES_PASSWORD: magento
      POSTGRES_DB: viewing_party
      TZ: 'America/Colorado'
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
