version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: bash -c "rm -f /app/tmp/pids/server.pid && rails db:{create,migrate} && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      - db
  db:
    image: postgres:14.6
    environment:
      POSTGRES_USER: party
      POSTGRES_PASSWORD: party
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
